//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Settings
{
	id: number;
	themeName: string;
}
export interface User
{
	id: string;
	firstName: string;
	lastName: string;
	fullName: string;
	email: string;
	age?: number;
	profileId: string;
	settings: Settings;
}
export interface Role
{
	name: string;
}
export interface SingUp extends LogIn
{
	fullName: string;
	confirmPassword: string;
}
export interface LogIn
{
	email: string;
	password: string;
}
export interface Token
{
}
export interface RefreshToken
{
	token: Token;
}
