//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Agenda
{
	id: string;
	day: number;
	startTime: Date;
	endTime?: Date;
	timeDuration?: number;
	productId: string;
	product: Product;
}
export interface Category
{
	id: string;
	categoryFatherId: string;
	categoryFather: Category;
	description: string;
	products: Product[];
	childrenCategories: Category[];
}
export interface Label
{
	id: string;
	name: string;
}
export interface Product
{
	id: string;
	fitnerId: string;
	productType: number;
	categoryId: string;
	category: Category;
	price: number;
	description: string;
	agendas: Agenda[];
	labels: Label[];
}
