//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Address
{
	id: string;
	country: string;
	state: string;
	city: string;
	postalCode: number;
	streetName: string;
	streetNumber: number;
	tower: number;
	floor: number;
	apartment: string;
	longitude: number;
	latitude: number;
}
export interface Fitner
{
	id: string;
	profileId: string;
	profile: Profile;
	groupId: string;
	group: Group;
}
export interface Group
{
	id: string;
	name: string;
	description: string;
	addressId: string;
	address: Address;
	fitnners: Fitner[];
}
export interface Profile
{
	id: string;
	name: string;
	description: string;
	avatar: string;
	addressId: string;
	address: Address;
}
